# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movie-list-tmdb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movie-list-tmdb
  pod 'Alamofire', '~> 4.5.0'
  pod 'ObjectMapper', '~> 2.2.8'
  pod 'AlamofireObjectMapper', '~> 4.1.0'
  pod 'AlamofireImage', '~> 3.1'
  pod 'SVProgressHUD', '~> 2.1.2'
  target 'movie-list-tmdbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'movie-list-tmdbUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
